# Generated by Django 4.1.4 on 2024-05-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTable',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'action_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentTable',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'assignment_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'category_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleTable',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'role_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketTable',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_subject', models.CharField(max_length=45)),
                ('ticket_description', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ticket_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phone_number', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
